<a href="https://colab.research.google.com/github/jeevang/test-repo/blob/master/testonvectarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,4,61,4])
print (a)
print (b)
print (a+b)


import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print (1000*(toc - tic))
print (c)

c = 0
tic - time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print (1000*(toc - tic))
print (c)

import matplotlib.pyplot as plt
import h5py
import scipy
from PIL import Image
from scipy import ndimage

%matplotlib inline


[1 2 3 4]
[ 2  4 61  4]
[ 3  6 64  8]
1.2371540069580078
249934.53651351944
365.16594886779785
249934.53651351677
